# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">= 1.1.7"
  required_providers {
    google = {
      version = "4.16.0"
    }
  }
}
provider "google" {
  project = "dev-testing-project-123124156"
}
